import {
  CH_FIRST_NAMES,
  CN_FIRST_NAMES,
  DE_FIRST_NAMES,
  EN_FIRST_NAMES,
  ES_FIRST_NAMES,
  FR_FIRST_NAMES,
  IN_FIRST_NAMES,
  IT_FIRST_NAMES,
  JP_FIRST_NAMES,
  KR_FIRST_NAMES,
  NL_FIRST_NAMES,
  PT_FIRST_NAMES,
  SE_FIRST_NAMES,
} from "@/constants/first-names.const";
import {
  CH_LAST_NAMES,
  CN_LAST_NAMES,
  DE_LAST_NAMES,
  EN_LAST_NAMES,
  ES_LAST_NAMES,
  FR_LAST_NAMES,
  IN_LAST_NAMES,
  IT_LAST_NAMES,
  JP_LAST_NAMES,
  KR_LAST_NAMES,
  NL_LAST_NAMES,
  PT_LAST_NAMES,
  SE_LAST_NAMES,
} from "@/constants/last-names.const";

interface Country {
  name: string;
  cities: string[];
  firstNames: string[];
  lastNames: string[];
}

export const COUNTRIES: Country[] = [
  {
    name: "USA",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "San Diego",
      "Dallas",
    ],
    firstNames: EN_FIRST_NAMES,
    lastNames: EN_LAST_NAMES,
  },
  {
    name: "Canada",
    cities: [
      "Toronto",
      "Vancouver",
      "Montreal",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
    ],
    firstNames: EN_FIRST_NAMES,
    lastNames: EN_LAST_NAMES,
  },
  {
    name: "UK",
    cities: [
      "London",
      "Manchester",
      "Birmingham",
      "Leeds",
      "Liverpool",
      "Bristol",
      "Glasgow",
    ],
    firstNames: EN_FIRST_NAMES,
    lastNames: EN_LAST_NAMES,
  },
  {
    name: "Australia",
    cities: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Canberra",
      "Darwin",
    ],
    firstNames: EN_FIRST_NAMES,
    lastNames: EN_LAST_NAMES,
  },
  {
    name: "Sweden",
    cities: [
      "Stockholm",
      "Gothenburg",
      "Malmö",
      "Uppsala",
      "Linköping",
      "Västerås",
      "Örebro",
    ],
    firstNames: SE_FIRST_NAMES,
    lastNames: SE_LAST_NAMES,
  },
  {
    name: "Netherlands",
    cities: [
      "Amsterdam",
      "Rotterdam",
      "Utrecht",
      "Eindhoven",
      "Groningen",
      "Maastricht",
      "Almere",
    ],
    firstNames: NL_FIRST_NAMES,
    lastNames: NL_LAST_NAMES,
  },
  {
    name: "France",
    cities: [
      "Paris",
      "Lyon",
      "Marseille",
      "Toulouse",
      "Bordeaux",
      "Nice",
      "Nantes",
    ],
    firstNames: FR_FIRST_NAMES,
    lastNames: FR_LAST_NAMES,
  },
  {
    name: "Germany",
    cities: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Dortmund",
      "Stuttgart",
      "Düsseldorf",
    ],
    firstNames: DE_FIRST_NAMES,
    lastNames: DE_LAST_NAMES,
  },
  {
    name: "Italy",
    cities: ["Rome", "Milan", "Naples", "Turin", "Genoa", "Palermo", "Bologna"],
    firstNames: IT_FIRST_NAMES,
    lastNames: IT_LAST_NAMES,
  },
  {
    name: "Switzerland",
    cities: [
      "Zurich",
      "Geneva",
      "Basel",
      "Lausanne",
      "Luzern",
      "Bern",
      "St. Gallen",
    ],
    firstNames: CH_FIRST_NAMES,
    lastNames: CH_LAST_NAMES,
  },
  {
    name: "Spain",
    cities: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Sevilla",
      "Bilbao",
      "Málaga",
      "Granada",
    ],
    firstNames: ES_FIRST_NAMES,
    lastNames: ES_LAST_NAMES,
  },
  {
    name: "Portugal",
    cities: [
      "Lisbon",
      "Porto",
      "Coimbra",
      "Vila Real",
      "Guimaraes",
      "Aveiro",
      "Cascais",
    ],
    firstNames: PT_FIRST_NAMES,
    lastNames: PT_LAST_NAMES,
  },
  {
    name: "Brazil",
    cities: [
      "Sao Paulo",
      "Rio de Janeiro",
      "Belo Horizonte",
      "Salvador",
      "Fortaleza",
      "Brasília",
      "Curitiba",
    ],
    firstNames: PT_FIRST_NAMES,
    lastNames: PT_LAST_NAMES,
  },
  {
    name: "Mexico",
    cities: [
      "Mexico City",
      "Guadalajara",
      "Monterrey",
      "Puebla",
      "Tijuana",
      "Cancún",
      "León",
    ],
    firstNames: ES_FIRST_NAMES,
    lastNames: ES_LAST_NAMES,
  },
  {
    name: "Chile",
    cities: [
      "Santiago",
      "Concepcion",
      "Valparaiso",
      "Antofagasta",
      "Temuco",
      "Valdivia",
      "Iquique",
    ],
    firstNames: ES_FIRST_NAMES,
    lastNames: ES_LAST_NAMES,
  },
  {
    name: "Japan",
    cities: [
      "Tokyo",
      "Osaka",
      "Fukuoka",
      "Nagoya",
      "Kobe",
      "Sapporo",
      "Hiroshima",
    ],
    firstNames: JP_FIRST_NAMES,
    lastNames: JP_LAST_NAMES,
  },
  {
    name: "South Korea",
    cities: [
      "Seoul",
      "Busan",
      "Daegwallyeong",
      "Incheon",
      "Daejeon",
      "Ulsan",
      "Gwangju",
    ],
    firstNames: KR_FIRST_NAMES,
    lastNames: KR_LAST_NAMES,
  },
  {
    name: "China",
    cities: [
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Shenzhen",
      "Chengdu",
      "Chongqing",
      "Tianjin",
    ],
    firstNames: CN_FIRST_NAMES,
    lastNames: CN_LAST_NAMES,
  },
  {
    name: "India",
    cities: [
      "Mumbai",
      "Delhi",
      "Bangalore",
      "Hyderabad",
      "Chennai",
      "Kolkata",
      "Pune",
    ],
    firstNames: IN_FIRST_NAMES,
    lastNames: IN_LAST_NAMES,
  },
];
